apiVersion: v1
kind: Service
metadata:
  name: lab
  namespace: ktu-stud-youstinus # TODO. Add your kubernetes namespace here. You can find your kubernetes namespace by running command: kubectl config view | grep namespace
spec:
  selector:
    app: lab
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080